- name: Install packages via pacman
  become: true
  pacman:
    state: present
    update_cache: true
    name: "{{ packages_common + packages_pacman }}"
  register: changed_pkgs

- name: Print changed packages
  debug: 
    msg: "{{ changed_pkgs }}"
